// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package google

import (
	"encoding/json"
	"reflect"

	"fmt"

	"github.com/spf13/pflag"
)

// If v is a pointer, it will get its element value or the zero value of the element type.
// If v is not a pointer, it will return it as is.
func (GKETokenSourceConfig) elemValueOrNil(v interface{}) interface{} {
	if t := reflect.TypeOf(v); t.Kind() == reflect.Ptr {
		if reflect.ValueOf(v).IsNil() {
			return reflect.Zero(t.Elem()).Interface()
		} else {
			return reflect.ValueOf(v).Interface()
		}
	} else if v == nil {
		return reflect.Zero(t).Interface()
	}

	return v
}

func (GKETokenSourceConfig) mustMarshalJSON(v json.Marshaler) string {
	raw, err := v.MarshalJSON()
	if err != nil {
		panic(err)
	}

	return string(raw)
}

// GetPFlagSet will return strongly types pflags for all fields in GKETokenSourceConfig and its nested types. The format of the
// flags is json-name.json-sub-name... etc.
func (cfg GKETokenSourceConfig) GetPFlagSet(prefix string) *pflag.FlagSet {
	cmdFlags := pflag.NewFlagSet("GKETokenSourceConfig", pflag.ExitOnError)
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "identityNamespace"), *new(string), "Defines workload identity namespace,  e.g. [project_id].svc.id.goog")
	cmdFlags.StringSlice(fmt.Sprintf("%v%v", prefix, "scope"), []string{}, "Defines OAuth 2.0 scopes to include on the resulting access token")
	cmdFlags.String(fmt.Sprintf("%v%v", prefix, "kubeConfig"), *new(string), "Path to Kubernetes client config file.")
	cmdFlags.Int(fmt.Sprintf("%v%v", prefix, "kubeClientConfig.burst"), *new(int), "Max burst rate for throttle. 0 defaults to 10")
	return cmdFlags
}
