// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package google

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/mitchellh/mapstructure"
	"github.com/stretchr/testify/assert"
)

var dereferencableKindsGKETokenSourceConfig = map[reflect.Kind]struct{}{
	reflect.Array: {}, reflect.Chan: {}, reflect.Map: {}, reflect.Ptr: {}, reflect.Slice: {},
}

// Checks if t is a kind that can be dereferenced to get its underlying type.
func canGetElementGKETokenSourceConfig(t reflect.Kind) bool {
	_, exists := dereferencableKindsGKETokenSourceConfig[t]
	return exists
}

// This decoder hook tests types for json unmarshaling capability. If implemented, it uses json unmarshal to build the
// object. Otherwise, it'll just pass on the original data.
func jsonUnmarshalerHookGKETokenSourceConfig(_, to reflect.Type, data interface{}) (interface{}, error) {
	unmarshalerType := reflect.TypeOf((*json.Unmarshaler)(nil)).Elem()
	if to.Implements(unmarshalerType) || reflect.PtrTo(to).Implements(unmarshalerType) ||
		(canGetElementGKETokenSourceConfig(to.Kind()) && to.Elem().Implements(unmarshalerType)) {

		raw, err := json.Marshal(data)
		if err != nil {
			fmt.Printf("Failed to marshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		res := reflect.New(to).Interface()
		err = json.Unmarshal(raw, &res)
		if err != nil {
			fmt.Printf("Failed to umarshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		return res, nil
	}

	return data, nil
}

func decode_GKETokenSourceConfig(input, result interface{}) error {
	config := &mapstructure.DecoderConfig{
		TagName:          "json",
		WeaklyTypedInput: true,
		Result:           result,
		DecodeHook: mapstructure.ComposeDecodeHookFunc(
			mapstructure.StringToTimeDurationHookFunc(),
			mapstructure.StringToSliceHookFunc(","),
			jsonUnmarshalerHookGKETokenSourceConfig,
		),
	}

	decoder, err := mapstructure.NewDecoder(config)
	if err != nil {
		return err
	}

	return decoder.Decode(input)
}

func join_GKETokenSourceConfig(arr interface{}, sep string) string {
	listValue := reflect.ValueOf(arr)
	strs := make([]string, 0, listValue.Len())
	for i := 0; i < listValue.Len(); i++ {
		strs = append(strs, fmt.Sprintf("%v", listValue.Index(i)))
	}

	return strings.Join(strs, sep)
}

func testDecodeJson_GKETokenSourceConfig(t *testing.T, val, result interface{}) {
	assert.NoError(t, decode_GKETokenSourceConfig(val, result))
}

func testDecodeSlice_GKETokenSourceConfig(t *testing.T, vStringSlice, result interface{}) {
	assert.NoError(t, decode_GKETokenSourceConfig(vStringSlice, result))
}

func TestGKETokenSourceConfig_GetPFlagSet(t *testing.T) {
	val := GKETokenSourceConfig{}
	cmdFlags := val.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())
}

func TestGKETokenSourceConfig_SetFlags(t *testing.T) {
	actual := GKETokenSourceConfig{}
	cmdFlags := actual.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())

	t.Run("Test_identityNamespace", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("identityNamespace"); err == nil {
				assert.Equal(t, string(*new(string)), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("identityNamespace", testValue)
			if vString, err := cmdFlags.GetString("identityNamespace"); err == nil {
				testDecodeJson_GKETokenSourceConfig(t, fmt.Sprintf("%v", vString), &actual.IdentityNamespace)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_scope", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vStringSlice, err := cmdFlags.GetStringSlice("scope"); err == nil {
				assert.Equal(t, []string([]string{}), vStringSlice)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := join_GKETokenSourceConfig("1,1", ",")

			cmdFlags.Set("scope", testValue)
			if vStringSlice, err := cmdFlags.GetStringSlice("scope"); err == nil {
				testDecodeSlice_GKETokenSourceConfig(t, join_GKETokenSourceConfig(vStringSlice, ","), &actual.Scope)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_kubeConfig", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("kubeConfig"); err == nil {
				assert.Equal(t, string(*new(string)), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("kubeConfig", testValue)
			if vString, err := cmdFlags.GetString("kubeConfig"); err == nil {
				testDecodeJson_GKETokenSourceConfig(t, fmt.Sprintf("%v", vString), &actual.KubeConfigPath)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_kubeClientConfig.burst", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vInt, err := cmdFlags.GetInt("kubeClientConfig.burst"); err == nil {
				assert.Equal(t, int(*new(int)), vInt)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("kubeClientConfig.burst", testValue)
			if vInt, err := cmdFlags.GetInt("kubeClientConfig.burst"); err == nil {
				testDecodeJson_GKETokenSourceConfig(t, fmt.Sprintf("%v", vInt), &actual.KubeConfig.Burst)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
}
